# Generated by Django 2.2.6 on 2019-11-06 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Entreprises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30, unique=True)),
                ('description', models.TextField(max_length=100, null=True)),
                ('nb_places', models.IntegerField(max_length=3)),
                ('nb_applicants', models.IntegerField(default=0, max_length=3)),
                ('CreationDate', models.DateTimeField(auto_now_add=True)),
                ('ExpDate', models.DateTimeField(null=True)),
                ('Status', models.BooleanField(null=True)),
                ('Entreprise', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Entreprises.Entreprise')),
            ],
        ),
    ]
