# Generated by Django 2.2.6 on 2019-11-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='ExpDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='offre',
            name='Status',
            field=models.BooleanField(null=True),
        ),
    ]
