# Generated by Django 2.2.6 on 2019-11-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='Entreprise',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='offer',
            name='Status',
            field=models.BooleanField(default=True),
        ),
    ]
