# Generated by Django 2.2.6 on 2019-11-03 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0002_auto_20191103_1618'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offre',
            new_name='Offer',
        ),
    ]
