# Generated by Django 2.2.6 on 2019-11-03 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offres', '0003_auto_20191103_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='nb_applicatns',
            new_name='nb_applicants',
        ),
    ]
