# Generated by Django 2.2.6 on 2019-11-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entreprises', '0002_entreprise_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
