# Generated by Django 2.2.6 on 2019-11-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entreprises', '0004_auto_20191106_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='password',
            field=models.CharField(default='', max_length=300),
        ),
    ]
