# Generated by Django 2.2.6 on 2019-11-16 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Entreprises', '0005_auto_20191108_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='adress',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='capital',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entreprise',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='employees',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='logo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='moto',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='sector',
            field=models.CharField(default='', max_length=100),
        ),
    ]
